_metadata_:
  version: '1.0'
  output_tag: ==done==
  save_figs: true
  description: Default generated profile
Nb_LINR1:
  notebook_id: LINR1
  notebook_dir: LinearReg
  notebook_src: 01-Linear-Regression.ipynb
  notebook_tag: default
Nb_GRAD1:
  notebook_id: GRAD1
  notebook_dir: LinearReg
  notebook_src: 02-Gradient-descent.ipynb
  notebook_tag: default
Nb_POLR1:
  notebook_id: POLR1
  notebook_dir: LinearReg
  notebook_src: 03-Polynomial-Regression.ipynb
  notebook_tag: default
Nb_LOGR1:
  notebook_id: LOGR1
  notebook_dir: LinearReg
  notebook_src: 04-Logistic-Regression.ipynb
  notebook_tag: default
Nb_PER57:
  notebook_id: PER57
  notebook_dir: IRIS
  notebook_src: 01-Simple-Perceptron.ipynb
  notebook_tag: default
Nb_BHPD1:
  notebook_id: BHPD1
  notebook_dir: BHPD
  notebook_src: 01-DNN-Regression.ipynb
  notebook_tag: default
Nb_BHPD2:
  notebook_id: BHPD2
  notebook_dir: BHPD
  notebook_src: 02-DNN-Regression-Premium.ipynb
  notebook_tag: default
Nb_MNIST1:
  notebook_id: MNIST1
  notebook_dir: MNIST
  notebook_src: 01-DNN-MNIST.ipynb
  notebook_tag: default
Nb_MNIST2:
  notebook_id: MNIST2
  notebook_dir: MNIST
  notebook_src: 02-CNN-MNIST.ipynb
  notebook_tag: default
Nb_GTSRB1:
  notebook_id: GTSRB1
  notebook_dir: GTSRB
  notebook_src: 01-Preparation-of-data.ipynb
  notebook_tag: default
  overrides:
    scale: default
    output_dir: default
Nb_GTSRB2:
  notebook_id: GTSRB2
  notebook_dir: GTSRB
  notebook_src: 02-First-convolutions.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    enhanced_dir: default
    dataset_name: default
    batch_size: default
    epochs: default
    scale: default
Nb_GTSRB3:
  notebook_id: GTSRB3
  notebook_dir: GTSRB
  notebook_src: 03-Tracking-and-visualizing.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    enhanced_dir: default
    dataset_name: default
    batch_size: default
    epochs: default
    scale: default
Nb_GTSRB4:
  notebook_id: GTSRB4
  notebook_dir: GTSRB
  notebook_src: 04-Data-augmentation.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    enhanced_dir: default
    dataset_name: default
    batch_size: default
    epochs: default
    scale: default
Nb_GTSRB5:
  notebook_id: GTSRB5
  notebook_dir: GTSRB
  notebook_src: 05-Full-convolutions.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    enhanced_dir: default
    datasets: default
    models: default
    batch_size: default
    epochs: default
    scale: default
    with_datagen: default
    verbose: default
Nb_GTSRB6:
  notebook_id: GTSRB6
  notebook_dir: GTSRB
  notebook_src: 06-Notebook-as-a-batch.ipynb
  notebook_tag: default
Nb_GTSRB7:
  notebook_id: GTSRB7
  notebook_dir: GTSRB
  notebook_src: 07-Show-report.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    report_dir: default
Nb_GTSRB10:
  notebook_id: GTSRB10
  notebook_dir: GTSRB
  notebook_src: batch_oar.sh
  notebook_tag: default
Nb_GTSRB11:
  notebook_id: GTSRB11
  notebook_dir: GTSRB
  notebook_src: batch_slurm.sh
  notebook_tag: default
Nb_IMDB1:
  notebook_id: IMDB1
  notebook_dir: IMDB
  notebook_src: 01-Embedding-Keras.ipynb
  notebook_tag: default
Nb_IMDB2:
  notebook_id: IMDB2
  notebook_dir: IMDB
  notebook_src: 02-Prediction.ipynb
  notebook_tag: default
Nb_IMDB3:
  notebook_id: IMDB3
  notebook_dir: IMDB
  notebook_src: 03-LSTM-Keras.ipynb
  notebook_tag: default
Nb_SYNOP1:
  notebook_id: SYNOP1
  notebook_dir: SYNOP
  notebook_src: 01-Preparation-of-data.ipynb
  notebook_tag: default
Nb_SYNOP2:
  notebook_id: SYNOP2
  notebook_dir: SYNOP
  notebook_src: 02-First-predictions.ipynb
  notebook_tag: default
  overrides:
    scale: default
    train_prop: default
    sequence_len: default
    batch_size: default
    epochs: default
Nb_SYNOP3:
  notebook_id: SYNOP3
  notebook_dir: SYNOP
  notebook_src: 03-12h-predictions.ipynb
  notebook_tag: default
  overrides:
    iterations: default
    scale: default
    train_prop: default
    sequence_len: default
    batch_size: default
    epochs: default
Nb_AE1:
  notebook_id: AE1
  notebook_dir: AE
  notebook_src: 01-AE-with-MNIST.ipynb
  notebook_tag: default
Nb_AE2:
  notebook_id: AE2
  notebook_dir: AE
  notebook_src: 02-AE-with-MNIST-post.ipynb
  notebook_tag: default
Nb_VAE1:
  notebook_id: VAE1
  notebook_dir: VAE
  notebook_src: 01-VAE-with-MNIST.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    scale: default
    latent_dim: default
    r_loss_factor: default
    batch_size: default
    epochs: default
Nb_VAE2:
  notebook_id: VAE2
  notebook_dir: VAE
  notebook_src: 02-VAE-with-MNIST-post.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
Nb_VAE5:
  notebook_id: VAE5
  notebook_dir: VAE
  notebook_src: 05-About-CelebA.ipynb
  notebook_tag: default
Nb_VAE6:
  notebook_id: VAE6
  notebook_dir: VAE
  notebook_src: 06-Prepare-CelebA-datasets.ipynb
  notebook_tag: default
  overrides:
    scale: default
    cluster_size: default
    image_size: default
    output_dir: default
    exit_if_exist: default
Nb_VAE7:
  notebook_id: VAE7
  notebook_dir: VAE
  notebook_src: 07-Check-CelebA.ipynb
  notebook_tag: default
  overrides:
    image_size: default
    enhanced_dir: default
Nb_VAE8:
  notebook_id: VAE8
  notebook_dir: VAE
  notebook_src: 08-VAE-with-CelebA.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    scale: default
    image_size: default
    enhanced_dir: default
    latent_dim: default
    r_loss_factor: default
    batch_size: default
    epochs: default
Nb_VAE9:
  notebook_id: VAE9
  notebook_dir: VAE
  notebook_src: 09-VAE-with-CelebA-post.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    image_size: default
    enhanced_dir: default
Nb_VAE10:
  notebook_id: VAE10
  notebook_dir: VAE
  notebook_src: batch_slurm.sh
  notebook_tag: default
Nb_ACTF1:
  notebook_id: ACTF1
  notebook_dir: Misc
  notebook_src: Activation-Functions.ipynb
  notebook_tag: default
Nb_NP1:
  notebook_id: NP1
  notebook_dir: Misc
  notebook_src: Numpy.ipynb
  notebook_tag: default
Nb_TSB1:
  notebook_id: TSB1
  notebook_dir: Misc
  notebook_src: Using-Tensorboard.ipynb
  notebook_tag: default
